import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — GlideDeck",
};

export default function TermsPage() {
  return (
    <article className="mx-auto max-w-3xl px-6 py-16">
      <h1 className="text-3xl font-bold">Terms of Service</h1>
      <p className="mt-2 text-sm text-slate-500">Last updated: March 22, 2026</p>

      <div className="mt-8 space-y-6 text-slate-700 dark:text-slate-300 [&_h2]:mt-8 [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:text-slate-900 dark:[&_h2]:text-white">
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using GlideDeck (&quot;the Service&quot;), you agree to be
          bound by these Terms of Service. If you do not agree, do not use the
          Service.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          GlideDeck is an AI-powered tool that creates and edits Google Slides
          presentations on your behalf. The Service requires a Google account
          and access to Google Slides and Google Drive APIs.
        </p>

        <h2>3. Account</h2>
        <p>
          You must sign in with a Google account to use the Service. You are
          responsible for maintaining the security of your account and for all
          activities that occur under your account.
        </p>

        <h2>4. Usage Limits</h2>
        <p>
          Free accounts are subject to monthly token limits and storage limits.
          We reserve the right to modify these limits at any time. Current
          limits are displayed on your account page within the application.
        </p>

        <h2>5. Your Content</h2>
        <p>
          You retain ownership of all content you create using GlideDeck.
          Presentations are stored in your Google Drive account. Uploaded images
          and brand assets are stored in our cloud storage and are accessible
          only to your account.
        </p>

        <h2>6. AI-Generated Content</h2>
        <p>
          Content generated by the AI is provided as-is. You are responsible for
          reviewing and verifying all AI-generated content before use. GlideDeck
          does not guarantee the accuracy, completeness, or appropriateness of
          AI-generated content.
        </p>

        <h2>7. Prohibited Use</h2>
        <p>You agree not to:</p>
        <ul className="list-disc space-y-1 pl-6">
          <li>Use the Service for any unlawful purpose</li>
          <li>Attempt to circumvent usage limits or security measures</li>
          <li>Use the Service to generate harmful, misleading, or abusive content</li>
          <li>Resell or redistribute the Service without permission</li>
        </ul>

        <h2>8. Limitation of Liability</h2>
        <p>
          The Service is provided &quot;as is&quot; without warranties of any kind.
          GlideDeck shall not be liable for any indirect, incidental, or
          consequential damages arising from your use of the Service.
        </p>

        <h2>9. Termination</h2>
        <p>
          We may suspend or terminate your access to the Service at any time for
          violation of these terms. You may stop using the Service at any time by
          revoking GlideDeck&apos;s access through your Google Account settings.
        </p>

        <h2>10. Changes to Terms</h2>
        <p>
          We may update these Terms from time to time. Continued use of the
          Service after changes constitutes acceptance of the updated Terms.
        </p>

        <h2>11. Contact</h2>
        <p>
          For questions about these Terms, contact us at{" "}
          <a
            href="mailto:support@glidedeck.ai"
            className="text-blue-600 underline hover:text-blue-700"
          >
            support@glidedeck.ai
          </a>
          .
        </p>
      </div>
    </article>
  );
}
